#!/bin/bash

passed=0
failed=0

# shellcheck disable=SC2034
output=$(./isabot -t Nzc1MjgyMjAyNzk0Nzg2ODE2.X6kD0Q.sTjKuY3GVQrDeLATD5lucvRAWb -v)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Bad token test: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t -v)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "No token test: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "No arguments test: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -h)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Help test: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot --help)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Help test_2: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot --help3)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Help test_3: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t -v)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Help -t -v: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t -v)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Help -t -v: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t NzY3NzUyNjc1MzM1ODY0MzMw.X42fZQ.SsoU2Wh_t5wVW7oe7KcvkE2f4dk -h )
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Token + help: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t NzY3NzUyNjc1MzM1ODY0MzMw.X42fZQ.SsoU2Wh_t5wVW7oe7KcvkE2f4dk --help )
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Token + help2: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t NzY3NzUyNjc1MzM1ODY0MzMw.X42fZQ.SsoU2Wh_t5wVW7oe7KcvkE2f4dk -h -v)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Token + help + v: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t NzY3NzUyNjc1MzM1ODY0MzMw.X42fZQ.SsoU2Wh_t5wVW7oe7KcvkE2f4dk --help --verbose)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Token + help + v2: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t NzY3NzUyNjc1MzM1ODY0MzMw.X42fZQ.SsoU2Wh_t5wVW7oe7KcvkE2f4dk -h --verbose)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "Token + help + v3: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot nejake hlupe argumenty ktore nepozna)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "nejake hlupe argumenty ktore nepozna: failed"
fi
sleep 1

# shellcheck disable=SC2034
output=$(./isabot -t-v-h)
if [ $? == 1 ]
then passed=$((passed+1))
else failed=$((failed+1))
	echo "-t-v-h: failed"
fi

echo $passed "passed from" $((passed + failed))